# Generated by Django 5.0.6 on 2024-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_alter_details_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
